### ISSUE TITLE
`@std/async/deadline` with `@std/testing/time` doesn't work

### ISSUE THREAD

**Issue by lambdalisue** [denoland/std#5499]
**Describe the bug**

The `Promise` returned from the `@std/async@1.0.0/deadline` (but from `@std/async@0.224.0/deadline`) won't be fulfilled by `FakeTime` from `@std/testing/time`.

**Steps to Reproduce**

```ts
import { delay } from "jsr:@std/async@1.0.0/delay";
import { assertEquals } from "jsr:@std/assert@1.0.0";
import { deadline as deadlineOld } from "jsr:@std/async@0.224.0/deadline";
import { deadline as deadlineNew } from "jsr:@std/async@1.0.0/deadline";
import { FakeTime } from "jsr:@std/testing/time";

Deno.test("deadline v0.224.0", async () => {
  using t = new FakeTime();
  const p = deadlineOld(delay(1000), 10);
  let state: "pending" | "rejected" | "fulfilled" = "pending";
  p.then(() => {
    state = "fulfilled";
  }).catch(() => {
    state = "rejected";
  });
  await t.tickAsync(10);
  await t.runMicrotasks();
  assertEquals(state, "rejected");
});

Deno.test("deadline v1.0.0", async () => {
  using t = new FakeTime();
  const p = deadlineNew(delay(1000), 10);
  let state: "pending" | "rejected" | "fulfilled" = "pending";
  p.then(() => {
    state = "fulfilled";
  }).catch(() => {
    state = "rejected";
  });
  await t.tickAsync(10);
  await t.runMicrotasks();
  assertEquals(state, "rejected");
});
```

And the result is

```
running 2 tests from ./deadline_test.ts
deadline v0.224.0 ... ok (4ms)
deadline v1.0.0 ... FAILED (6ms)

 ERRORS 

deadline v1.0.0 => ./deadline_test.ts:21:6
error: AssertionError: Values are not equal.


    [Diff] Actual / Expected


-   pending
+   rejected


  throw new AssertionError(message);
        ^
    at assertEquals (https://jsr.io/@std/assert/1.0.0/equals.ts:47:9)
    at file:///D:/work/vim/denops.vim/deadline_test.ts:32:3

 FAILURES 

deadline v1.0.0 => ./deadline_test.ts:21:6

FAILED | 1 passed | 1 failed (15ms)

error: Test failed
```

**Expected behavior**

The test pass.

**Environment**

- OS: macOS Sonoma
- deno version: v1.45.2
- std version: v1.0.0

**Comment by Milly** [comment]
I'm doing a PR on this now.
