### ISSUE TITLE
assertEquals doesn't work for large arrays

### ISSUE THREAD

**Issue by sigmaSd** [denoland/std#5942]
```ts
import { assertEquals } from "jsr:@std/assert@1";
const a = Deno.readFileSync(Deno.execPath());
assertEquals(a, new Uint8Array());
```
`deno -R a.ts`

```
error: Uncaught (in promise) RangeError: Invalid array length
      if (Object.keys(a).length !== Object.keys(b).length) {
```

**Comment by kt3k** [comment]
Does the utility like this make more sense to such cases? https://github.com/fent/node-stream-equal

**Comment by sigmaSd** [comment]
I'm not sure it feels weird to me that an assert equal doesn't work after a certain size, also the error is not helpful

**Comment by lionel-rowe** [comment]
It'd probably make sense to have a separate path for iterables and/or array-likes.

```ts
type Iter<T> = { [Symbol.iterator](): Iterator<T> };
type TypedArrayLike = Iter<number | bigint>;
function isTypedArray(x: unknown): x is TypedArrayLike {
    return ArrayBuffer.isView(x) && Symbol.iterator in x;
}

function iterEqual<A, B>(a: Iter<A>, b: Iter<B>, eq: (a: A, b: B) => boolean): boolean {
    if (a.constructor !== b.constructor) return false
    // @ts-expect-error - if no `length` prop we just check both undefined
    if (a.length !== b.length) return false
    
    const aIter = a[Symbol.iterator]();
    const bIter = b[Symbol.iterator]();
    
    while (true) {
        const aNext = aIter.next();
        const bNext = bIter.next();
        if (aNext.done !== bNext.done) return false;
        if (!eq(aNext.value, bNext.value)) return false;
        if (aNext.done) return true;
    }
}

function typedArrayEqual(a: TypedArrayLike, b: TypedArrayLike): boolean {
    return iterEqual(a, b, (a, b) => a === b);
}

const a = Deno.readFileSync(Deno.execPath());
const b = Deno.readFileSync(Deno.execPath());
const c = new Uint8Array();
console.time()
// true
console.log(typedArrayEqual(a, b));
// 3562ms
console.timeEnd()

b[b.length - 1] = 255;
console.time()
// false
console.log(typedArrayEqual(a, b));
// 3381ms
console.timeEnd()

console.time()
// false
console.log(typedArrayEqual(a, c));
// 0ms
console.timeEnd()
```

**Comment by Jamesernator** [comment]
This still occurs for arrays (and typed arrays), now with a failed `ArrayBuffer` allocation.

A minimal example:

```
> assert.assertEquals(Array.from({ length: 2**18 }, () => Math.random()), Array.from({ length: 2**18 }))
Uncaught RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new Uint32Array (<anonymous>)
    at diff (file:///home/jamesernator/projects/deno-std/internal/diff.ts:270:18)
    at Module.assertEquals (file:///home/jamesernator/projects/deno-std/assert/equals.ts:63:7)
    at <anonymous>:1:29
```

It seems that [`diff` tries to allocate a byte array that is too large for v8](https://github.com/denoland/std/blob/main/internal/diff.ts#L270). In cases like this it would probably be better just to report where the first difference in the two arrays is instead of trying to compute a full diff.
