### ISSUE TITLE
@std/fs exists does not work on Deno.execPath()

### ISSUE THREAD

**Issue by tiloio** [denoland/std#6125]
The following code should give a false result:
```ts

import { exists } from "jsr:@std/fs@1.0.4";
import * as path from "jsr:@std/path@1.0.6";

const result = await exists(
  path.join(Deno.execPath(), "not_existing_file_or_dir")
);

console.log(result);
```

This script will result in:
```sh
error: Uncaught (in promise) Error: Not a directory (os error 20): stat '/opt/homebrew/bin/deno/not_existing_file_or_dir'
    const stat = await Deno.stat(path);
                 ^
    at async Object.stat (ext:deno_fs/30_fs.js:407:15)
    at async exists (https://jsr.io/@std/fs/1.0.4/exists.ts:129:18)
    at async THE_CODE:4:16
```

I think the following code should respect the "Not a directory"-Error: https://github.com/denoland/std/blob/45be5d319dde70c3901ca24294936e95a8a7f0be/fs/exists.ts#L150

**Comment by tiloio** [comment]
I did not unterstand the error - after I realizied that the execPath is a file and not a directory the error is clear...
