### ISSUE TITLE
Short-circuit in starts_with

### ISSUE THREAD

**Issue by ozanmuyes** [denoland/std#6146]
https://github.com/denoland/std/blob/10ee73dbbcf6e55fca62d1dccb7c086911030f28/bytes/starts_with.ts#L27

this can be written as
```javascript
         if (prefix.length != source.length) {
```

since `prefix` can't be longer than the `source`.

**Comment by babiabeo** [comment]
It will return `false` if `prefix` is shorter than `source`, which is not the expected behavior.

**Comment by ozanmuyes** [comment]
Why it is not the expected behaviour? So "foobar" starts with "foobarbaz"?

**Comment by 0f-0b** [comment]
This is what happens if you run the [example from the documentation](https://jsr.io/@std/bytes/doc/starts-with/~/startsWith#example_0) after applying this change.

```shellsession
$ deno run example.ts
error: Uncaught (in promise) AssertionError: Values are not equal.


    [Diff] Actual / Expected


-   false
+   true

  throw new AssertionError(message);
        ^
    at assertEquals (file://…/deno_std/assert/equals.ts:51:9)
    at file://…/example.ts:7:1
```

If you remove the check altogether it would work, but much slower than the original in case `prefix` is sometimes longer than `source`, because V8 deoptimizes the function when `source[i]` indexes out of bounds.

**Comment by WWRS** [comment]
For a concrete example (using strings),

```
const source = "foobar";
startsWith(source, "foo");  // should be true
startsWith(source, "foobar");  // should be true
startsWith(source, "foobarbaz"); // should be false
```

The first assertion has `prefix.length < source.length`, the second has `prefix.length === source.length`, and the third has `prefix.length > source.length`. The existing short circuit logic handles the third case. The proposed change would cause the first case to short circuit with `false` which is not right because "foobar" does start with "foo".
